version: '3'
services:
    web:
        build: .
        ports:
            - "8050:8050"
    
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/cert.pem:/etc/ssl/cert.pem
            - ./nginx/cert.key:/etc/ssl/cert.key
        ports:
            - "80:80"
            - "443:443"